### ISSUE TITLE
preference_api crash on close

### ISSUE THREAD

**Issue by jjblum** [platypusllc/tablet#27]
When you swipe the app to close it, it crashes:

> AndroidRuntime                [E] FATAL EXCEPTION: main                                                                                                                         
AndroidRuntime                [E] Process: com.platypus.android.tablet, PID: 3124                                                                                               
AndroidRuntime                [E] Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overl
                                  ay:system}                                                                                                                                    
AndroidRuntime                [E] java.lang.RuntimeException: Unable to destroy activity {com.platypus.android.tablet/com.platypus.android.tablet.TeleOpPanel}: java.lang.NullPo
                                  interException: Attempt to invoke virtual method 'double com.mapbox.mapboxsdk.geometry.LatLng.getLatitude()' on a null object reference       
AndroidRuntime                [E] at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3875)                                                                
AndroidRuntime                [E] at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3893)                                                                 
AndroidRuntime                [E] at android.app.ActivityThread.-wrap5(ActivityThread.java)                                                                                     
AndroidRuntime                [E] at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)                                                                       
AndroidRuntime                [E] at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                       
AndroidRuntime                [E] at android.os.Looper.loop(Looper.java:148)                                                                                                    
AndroidRuntime                [E] at android.app.ActivityThread.main(ActivityThread.java:5466)                                                                                  
AndroidRuntime                [E] at java.lang.reflect.Method.invoke(Native Method)                                                                                             
AndroidRuntime                [E] at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)                                                            
AndroidRuntime                [E] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)                                                                               
AndroidRuntime                [E] Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double com.mapbox.mapboxsdk.geometry.LatLng.getLatitude()' on a n
                                  ull object reference                                                                                                                          
AndroidRuntime                [E] at com.platypus.android.tablet.TeleOpPanel.onDestroy(TeleOpPanel.java:946)                                                                    
AndroidRuntime                [E] at android.app.Activity.performDestroy(Activity.java:6422)                                                                                    
AndroidRuntime                [E] at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)                                                               
AndroidRuntime                [E] at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3862)                                                                
AndroidRuntime                [E] ... 9 more

**Comment by jjblum** [comment]
Does not crash if you have a boat gps fix. Including the next issue (crash using drop waypoint without boat gps fix, another null pointer exception), it looks like you should look through the code for any time you try to get boat position, and protect against nulls.
