### ISSUE TITLE
crash using "Drop Waypoint" without a boat fix

### ISSUE THREAD

**Issue by jjblum** [platypusllc/tablet#28]
If a user plays with the app and there isn't a boat connected, they can crash it by pressing the drop waypoint button. 

AndroidRuntime                [E] FATAL EXCEPTION: main                                                                                                                         
AndroidRuntime                [E] Process: com.platypus.android.tablet, PID: 3767                                                                                               
AndroidRuntime                [E] Theme: themes:{default=overlay:system, iconPack:system, fontPkg:system, com.android.systemui=overlay:system, com.android.systemui.navbar=overl
                                  ay:system}                                                                                                                                    
AndroidRuntime                [E] java.lang.NullPointerException                                                                                                                
AndroidRuntime                [E] at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddPolylines(Native Method)                                                                  
AndroidRuntime                [E] at com.mapbox.mapboxsdk.maps.NativeMapView.addPolyline(NativeMapView.java:376)                                                                
AndroidRuntime                [E] at com.mapbox.mapboxsdk.maps.MapView.addPolyline(MapView.java:1185)                                                                           
AndroidRuntime                [E] at com.mapbox.mapboxsdk.maps.MapboxMap.addPolyline(MapboxMap.java:1226)                                                                       
AndroidRuntime                [E] at com.platypus.android.tablet.TeleOpPanel.invalidate(TeleOpPanel.java:3003)                                                                  
AndroidRuntime                [E] at com.platypus.android.tablet.TeleOpPanel$37.onClick(TeleOpPanel.java:2639)                                                                  
AndroidRuntime                [E] at android.view.View.performClick(View.java:5204)                                                                                             
AndroidRuntime                [E] at android.view.View$PerformClick.run(View.java:21156)                                                                                        
AndroidRuntime                [E] at android.os.Handler.handleCallback(Handler.java:739)                                                                                        
AndroidRuntime                [E] at android.os.Handler.dispatchMessage(Handler.java:95)                                                                                        
AndroidRuntime                [E] at android.os.Looper.loop(Looper.java:148)                                                                                                    
AndroidRuntime                [E] at android.app.ActivityThread.main(ActivityThread.java:5466)                                                                                  
AndroidRuntime                [E] at java.lang.reflect.Method.invoke(Native Method)                                                                                             
AndroidRuntime                [E] at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)                                                            
AndroidRuntime                [E] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jjblum** [comment]
Quick fix:
change TeleOpPanel.java line 2700
FROM 
`if (currentBoat != null || currentBoat.getLocation() != null || mMapboxMap != null)`

TO 
`if (currentBoat != null && currentBoat.getLocation() != null && mMapboxMap != null)`
