### ISSUE TITLE
set home to tablet location crash

### ISSUE THREAD

**Issue by jjblum** [platypusllc/tablet#40]
AndroidRuntime                [E] FATAL EXCEPTION: main                                                                                                                         
AndroidRuntime                [E] Process: com.platypus.android.tablet, PID: 4357                                                                                               
AndroidRuntime                [E] java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference  
AndroidRuntime                [E] at com.platypus.android.tablet.TeleOpPanel$20.onClick(TeleOpPanel.java:1995)                                                                  
AndroidRuntime                [E] at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)                                             
AndroidRuntime                [E] at android.os.Handler.dispatchMessage(Handler.java:102)                                                                                       
AndroidRuntime                [E] at android.os.Looper.loop(Looper.java:135)                                                                                                    
AndroidRuntime                [E] at android.app.ActivityThread.main(ActivityThread.java:5466)                                                                                  
AndroidRuntime                [E] at java.lang.reflect.Method.invoke(Native Method)                                                                                             
AndroidRuntime                [E] at java.lang.reflect.Method.invoke(Method.java:372)                                                                                           
AndroidRuntime                [E] at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)                                                            
AndroidRuntime                [E] at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by christomaszewski** [comment]
Looks like we need a check to see if the location has been acquired by the tablet. Tried to replicate this on my setup but the tablet got a location and set home worked fine.
